# Generated by Django 2.0 on 2018-05-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Quadrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_relative_pos_x', models.IntegerField()),
                ('map_relative_pos_y', models.IntegerField()),
                ('max_coordinates',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quadrant_max',
                                   to='map.Coordinates')),
                ('min_coordinates',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quadrant_min',
                                   to='map.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='ReportQuadrantAggregationSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('report_total_count', models.IntegerField()),
                ('report_w_intensity_count', models.IntegerField()),
                ('intensity_sum', models.IntegerField()),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Quadrant')),
            ],
        ),
    ]
