# Generated by Django 2.0 on 2018-06-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportquadrantaggregationslice',
            name='intensity_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportquadrantaggregationslice',
            name='report_total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportquadrantaggregationslice',
            name='report_w_intensity_count',
            field=models.IntegerField(default=0),
        ),
    ]
