# Generated by Django 2.0 on 2018-06-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_reportquadrantaggregationslice_points_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkType',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='landmark',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='map.LandmarkType'),
        ),
    ]
