# Generated by Django 2.0 on 2018-04-18 16:34

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('elevation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on',
                 models.DateTimeField(default=datetime.datetime(2018, 4, 18, 16, 34, 2, 30638, tzinfo=utc),
                                      editable=False)),
                ('modified_on',
                 models.DateTimeField(default=datetime.datetime(2018, 4, 18, 16, 34, 2, 30685, tzinfo=utc))),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('coordinates',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_res.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.Report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='threatreport',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.ThreatType'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.Report'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.EmergencyType'),
        ),
        migrations.AlterUniqueTogether(
            name='threatreport',
            unique_together={('type', 'report')},
        ),
        migrations.AlterUniqueTogether(
            name='emergencyreport',
            unique_together={('type', 'report')},
        ),
    ]
