# Generated by Django 2.0 on 2018-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntensityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('intensity', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['intensity'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('username', models.TextField()),
                ('coordinates',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_res.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.Report')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.Threat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.Report'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_res.Emergency'),
        ),
        migrations.AlterUniqueTogether(
            name='threatreport',
            unique_together={('type', 'report')},
        ),
        migrations.AlterUniqueTogether(
            name='emergencyreport',
            unique_together={('type', 'report')},
        ),
    ]
