# Generated by Django 2.0 on 2018-05-09 14:37

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('mobile_res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.Coordinates'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 14, 37, 25, 835445, tzinfo=utc),
                                       editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 14, 37, 25, 835495, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
