# Generated by Django 2.0 on 2018-05-18 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quake',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 20, 6, 37, 37553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quake',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 20, 6, 37, 37553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 20, 6, 37, 37553, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 20, 6, 37, 37553, tzinfo=utc)),
        ),
    ]
